
import type { FastifyInstance } from 'fastify';
import type { ZodTypeProvider } from 'fastify-type-provider-zod';

import { prisma } from '@aquarium/database';
import { getAuthenticatedUser } from '../lib/get-authenticated-user.js';
import { fishIdParamsSchema } from '../schemas/fish.schema.js';

import {
  mkdir,
  readFile,
  writeFile,
  unlink,
} from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { isNativeError } from 'node:util/types';

const STORAGE_DIR =
  process.env.STORAGE_DIR ??
  join(process.cwd(), 'storage', 'fish-textures');

const MAX_FILE_SIZE = 5 * 1024 * 1024;

const PNG_SIGNATURE = Buffer.from([
  137, 80, 78, 71, 13, 10, 26, 10,
]);

const TEXTURE_KEY_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.png$/i;

export async function fishTextureRoutes(app: FastifyInstance) {
  const api = app.withTypeProvider<ZodTypeProvider>();

  // Download a fish's painted texture.
  api.get(
    '/fish/:id/texture',
    {
      schema: {
        params: fishIdParamsSchema,
      },
    },
    async (request, reply) => {
      const user = await getAuthenticatedUser(request);

      if (!user) {
        return reply.code(401).send({
          error: 'Unauthorized',
        });
      }

      const fish = await prisma.fish.findFirst({
        where: {
          id: request.params.id,
          ownerId: user.id,
        },
        select: {
          paintKey: true,
        },
      });

      if (!fish) {
        return reply.code(404).send({
          error: 'Fish not found',
        });
      }

      if (!fish.paintKey) {
        return reply.code(404).send({
          error: 'Fish has no painted texture',
        });
      }

      // Only accept filenames generated by our upload route.
      if (!TEXTURE_KEY_PATTERN.test(fish.paintKey)) {
        request.log.error(
          { paintKey: fish.paintKey },
          'Invalid stored texture key',
        );

        return reply.code(500).send({
          error: 'Invalid stored texture key',
        });
      }

      const filePath = join(STORAGE_DIR, fish.paintKey);

      let buffer: Buffer;

      try {
        buffer = await readFile(filePath);
      } catch (error) {
        if (
          isNativeError(error) &&
          'code' in error &&
          error.code === 'ENOENT'
        ) {
          return reply.code(404).send({
            error: 'Texture file not found',
          });
        }

        throw error;
      }

      return reply
        .type('image/png')
        .header('Cache-Control', 'private, no-store')
        .send(buffer);
    },
  );

  // Upload or replace a fish's painted texture.
  api.post(
    '/fish/:id/texture',
    {
      schema: {
        params: fishIdParamsSchema,
      },
    },
    async (request, reply) => {
      const user = await getAuthenticatedUser(request);

      if (!user) {
        return reply.code(401).send({
          error: 'Unauthorized',
        });
      }

      const fish = await prisma.fish.findFirst({
        where: {
          id: request.params.id,
          ownerId: user.id,
        },
        select: {
          id: true,
          paintKey: true,
        },
      });

      if (!fish) {
        return reply.code(404).send({
          error: 'Fish not found',
        });
      }

      if (!request.isMultipart()) {
        return reply.code(415).send({
          error: 'Expected multipart/form-data',
        });
      }

      const file = await request.file({
        limits: {
          fileSize: MAX_FILE_SIZE,
        },
      });

      if (!file) {
        return reply.code(400).send({
          error: 'No file uploaded',
        });
      }

      if (
        file.fieldname !== 'texture' ||
        file.mimetype !== 'image/png'
      ) {
        // Consume the stream before returning.
        file.file.resume();

        return reply.code(415).send({
          error: 'Expected a PNG file in the texture field',
        });
      }

      const buffer = await file.toBuffer();

      // Check actual PNG signature, not just MIME type.
      if (
        buffer.length < PNG_SIGNATURE.length ||
        !buffer.subarray(0, 8).equals(PNG_SIGNATURE)
      ) {
        return reply.code(400).send({
          error: 'Invalid PNG file',
        });
      }

      await mkdir(STORAGE_DIR, {
        recursive: true,
      });

      const paintKey = `${randomUUID()}.png`;
      const filePath = join(STORAGE_DIR, paintKey);

      await writeFile(filePath, buffer, {
        flag: 'wx',
      });

      try {
        const updated = await prisma.fish.updateMany({
          where: {
            id: fish.id,
            ownerId: user.id,
          },
          data: {
            paintKey,
          },
        });

        if (updated.count === 0) {
          await unlink(filePath).catch(() => {});

          return reply.code(404).send({
            error: 'Fish not found',
          });
        }
      } catch (error) {
        // Don't leave orphaned files if the database update fails.
        await unlink(filePath).catch(() => {});

        throw error;
      }

      // Remove the previous texture after the new one is saved.
      if (
        fish.paintKey &&
        fish.paintKey !== paintKey &&
        TEXTURE_KEY_PATTERN.test(fish.paintKey)
      ) {
        await unlink(join(STORAGE_DIR, fish.paintKey)).catch(
          (error: unknown) => {
            request.log.warn(
              { err: error },
              'Could not remove previous texture',
            );
          },
        );
      }

      return reply.send({
        fishId: fish.id,
        paintKey,
        message: 'Texture uploaded successfully',
      });
    },
  );
}
